version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - restore_cache:
          key: testmints-cache-7-{{ .Branch }}
      - run: "./gradlew check release closeAndReleaseSonatypeStagingRepository --stacktrace"
      - save_cache:
          key: testmints-cache-7-{{ .Branch }}
          paths:
            - buildSrc/build
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  build-mac:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout
      - restore_cache:
          key: testmints-mac-cache-3-{{ .Branch }}
      - run: "git tag -d $(git describe) || echo 'no fail'"
      - run: "./gradlew -P release-target=mac release closeAndReleaseSonatypeStagingRepository"
      - save_cache:
          key: testmints-mac-cache-3-{{ .Branch }}
          paths:
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: "gradlew.bat --no-daemon -s -i mingwX64Test"
  update-libs:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - run: "./gradlew useLatestVersions"
      - run: "./gradlew check release --stacktrace"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - run: "git add ."
      - run: "git config user.email \"robert.f.murdock@gmail.com\""
      - run: "git config user.name \"CircleCI in a RoB Suit\""
      - run: "git commit -m '[patch] Automatic dependency update.' || echo 'Ignoring no changes'"
      - run: "git push"
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-linux
      - build-mac
  update-libs:
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-libs
