version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:17.0
        environment:
          GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
          _JAVA_OPTIONS: "-Xmx3g"
    steps:
      - run: "sudo apt-get update"
      - run: "sudo apt-get install libncurses5"
      - checkout
      - restore_cache:
          key: testmints-cache-9-{{ .Branch }}
      - run: "./gradlew check release closeAndReleaseSonatypeStagingRepository --stacktrace"
      - save_cache:
          key: testmints-cache-9-{{ .Branch }}
          paths:
            - buildSrc/build
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
  build-mac:
    macos:
      xcode: "13.1.0"
    steps:
      - checkout
      - restore_cache:
          key: testmints-mac-cache-4-{{ .Branch }}
      - run: "git tag -d $(git describe) || echo 'no fail'"
      - run: "./gradlew -P release-target=mac release closeAndReleaseSonatypeStagingRepository"
      - save_cache:
          key: testmints-mac-cache-4-{{ .Branch }}
          paths:
            - "~/.gradle"
            - "~/.konan"
            - ".gradle"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: "gradlew.bat --no-daemon -s -i mingwX64Test"
  update-libs:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: "sudo apt-get update"
      - run: "sudo apt-get install libncurses5"
      - checkout
      - run: "./gradlew :plugins:useLatestVersions useLatestVersions"
      - run: "./gradlew model"
      - run: "./gradlew check release --stacktrace"
      - store_artifacts:
          path: build/test-output
      - store_test_results:
          path: build/test-output
      - run: "git add ."
      - run: "git config user.email \"robert.f.murdock@gmail.com\""
      - run: "git config user.name \"CircleCI in a RoB Suit\""
      - run: "git commit -m '[patch] Automatic dependency update.' || echo 'Ignoring no changes'"
      - run: "git push"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-linux
      - build-mac
  update-libs:
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-libs
