name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-job:
    name: "Build Linux"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TESTMINTS_PAT }}
      GITHUB_TOKEN: ${{ secrets.TESTMINTS_PAT }}
      GRGIT_USER: ${{ secrets.TESTMINTS_PAT }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: robertfmurdock
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Build
        run: ./gradlew release check --scan -Porg.gradle.parallel=false
      - run: git status
        if: ${{ always() }}
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-output
          path: |
            build/test-output/
      - name: Push result to Testspace server
        if: always()
        run: |
          testspace $(find . -path *test-results* -name *.xml)
  build-job-mac:
    name: "Build Mac"
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.TESTMINTS_PAT }}
      GITHUB_TOKEN: ${{ secrets.TESTMINTS_PAT }}
      GRGIT_USER: ${{ secrets.TESTMINTS_PAT }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: robertfmurdock
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - name: Build
        run: ./gradlew release --scan -Porg.gradle.parallel=false -Prelease-target=mac
      - run: git status
        if: ${{ always() }}
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-output
          path: |
            build/test-output/
      - name: Push result to Testspace server
        if: always()
        run: |
          testspace $(find . -path *test-results* -name *.xml)