name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '25'
      - name: Update Gradle Wrapper
        id: update-gradle-wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.TESTMINTS_PAT }}
          pull-request-number: ${{ steps.update-gradle-wrapper.pull_request_data.number }}
          merge-method: rebase
